spring.application.name=demo
spring.datasource.url= jdbc:postgresql://localhost:5432/Mobile
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
server.port=8081

#enable simple cache- store cache in jvm memeory
spring.cache.type=simple

#enable actuator end point all
management.endpoints.web.exposure.include=*
